// app/contact-us/page.tsx
	// Auto-generated by Theme Editor - Do not edit manually

	import ClientPage from './ClientPage';

	export async function generateMetadata() {
		return {
			title: "Contact Us",
			description: "",
		};
	}

	export default function GeneratedPage() {
		// Embedded theme and page data
		const themeData = {
        "company_id": 1,
        "company_uid": "1BUPSJZ67YZ",
        "date_added": "2026-04-16 07:44:53",
        "hosting_info": {
            "github_client_id": "Ov23liumfD4QjywcPtSo",
            "github_repo_clone_url": "https://github.com/oluwapaso/houxera-test-14.git",
            "github_repo_default_branch": "main",
            "github_repo_description": "houxera-test-14",
            "github_repo_full_name": "oluwapaso/houxera-test-14",
            "github_repo_html_url": "https://github.com/oluwapaso/houxera-test-14",
            "github_repo_language": "\u003cnil\u003e",
            "github_repo_name": "houxera-test-14",
            "github_repo_ssh_url": "git@github.com:oluwapaso/houxera-test-14.git",
            "github_repo_updated_at": "2026-05-28T13:14:31Z",
            "github_repo_visibility": "public"
        },
        "idx_theme_id": 1,
        "idx_theme_uid": "68f4dc1c-2881-4d61-a53e-fa360551d522",
        "status": "Draft",
        "theme_settings": {
            "bg_solid_primary_color": "bg-green-600",
            "blog_card": "BlogCard-1",
            "footer_component": "FooterVar1",
            "footer_menu": [
                {
                    "isDefault": false,
                    "sub_menu": [
                        {
                            "link": "/buying-homes-in-lekki",
                            "title": "Buying Homes"
                        },
                        {
                            "link": "/selling-homes-in-lekki",
                            "title": "Selling Homes"
                        }
                    ],
                    "title": "Discover Services"
                },
                {
                    "isDefault": true,
                    "sub_menu": [
                        {
                            "link": "/buying-homes-in-lekki",
                            "title": "Buying Homes"
                        },
                        {
                            "link": "/selling-homes-in-lekki",
                            "title": "Selling Homes"
                        }
                    ],
                    "title": "Popular Links"
                },
                {
                    "isDefault": false,
                    "sub_menu": [
                        {
                            "link": "/aja-properties",
                            "title": "Aja"
                        },
                        {
                            "link": "/lekki-properties",
                            "title": "Lekki"
                        }
                    ],
                    "title": "Popular Areas In Lagos"
                }
            ],
            "header_component": "Header-1",
            "is_default": "No",
            "name": "theme name here",
            "nav_component": "NavVar1",
            "pages": [],
            "primary_color": "green-600",
            "primary_font": "Poppins",
            "property_card": "PropertyCard-1",
            "secondary_color": "gray-900",
            "secondary_font": "Jost",
            "service_card": "ServiceCard-1",
            "solid_primary_color": "sky-600",
            "solid_secondary_color": "blue-500",
            "solid_sencondary_color": "gray-800",
            "solid_tetiary_color": "amber-600",
            "tetiary_color": "fuchsia-500",
            "theme_prefix": "",
            "top_menu": [
                {
                    "isDefault": true,
                    "link": "/",
                    "title": "Home"
                },
                {
                    "isDefault": true,
                    "sub_menu": [
                        {
                            "link": "/buying-homes-in-lekki",
                            "title": "Buying Homes"
                        },
                        {
                            "link": "/selling-homes-in-lekki",
                            "title": "Selling Home"
                        },
                        {
                            "link": "/property-mortgage",
                            "title": "Mortgage"
                        }
                    ],
                    "title": "Our Services"
                },
                {
                    "sub_menu": [
                        {
                            "link": "/more-menu-1",
                            "title": "More Menu 1"
                        },
                        {
                            "link": "/more-menu-2",
                            "title": "More Menu 2"
                        }
                    ],
                    "title": "New Menu"
                },
                {
                    "isDefault": false,
                    "link": "/contact-us",
                    "title": "Contact Us"
                }
            ],
            "version": "1.0.1"
        },
        "title": "Initial Theme Test",
        "user_id": 1,
        "website": "https://themetest.com"
    };
		const pageData = {
        "isHome": false,
        "metaDescription": "",
        "sections": [
            {
                "props": {
                    "button_text": "Send Us Message",
                    "category": "contact_us_form",
                    "component": "ContactUsFormVar1",
                    "header": "Want To Talk",
                    "name": "Contact Us Form",
                    "sub_header": "It's all about the humans behind a brand and those experiencing it, we're right there. In the middle.",
                    "type": "section"
                },
                "type": "ContactUsFormVar1"
            }
        ],
        "slug": "/contact-us",
        "title": "Contact Us",
        "uid": "contact-us-001"
    };

		return <ClientPage themeData={themeData} pageData={pageData} />;
	}