// app/home/page.tsx
	// Auto-generated by Theme Editor - Do not edit manually

	import ClientPage from './ClientPage';

	export async function generateMetadata() {
		return {
			title: "Lagos Realty: Home Page",
			description: "",
		};
	}

	export default function GeneratedPage() {
		// Embedded theme and page data
		const themeData = {
        "company_id": 1,
        "company_uid": "1BUPSJZ67YZ",
        "date_added": "2026-04-16 07:44:53",
        "hosting_info": {
            "github_client_id": "Ov23liumfD4QjywcPtSo",
            "github_repo_clone_url": "https://github.com/oluwapaso/houxera-test-14.git",
            "github_repo_default_branch": "main",
            "github_repo_description": "houxera-test-14",
            "github_repo_full_name": "oluwapaso/houxera-test-14",
            "github_repo_html_url": "https://github.com/oluwapaso/houxera-test-14",
            "github_repo_language": "\u003cnil\u003e",
            "github_repo_name": "houxera-test-14",
            "github_repo_ssh_url": "git@github.com:oluwapaso/houxera-test-14.git",
            "github_repo_updated_at": "2026-05-28T13:14:31Z",
            "github_repo_visibility": "public"
        },
        "idx_theme_id": 1,
        "idx_theme_uid": "68f4dc1c-2881-4d61-a53e-fa360551d522",
        "status": "Draft",
        "theme_settings": {
            "bg_solid_primary_color": "bg-green-600",
            "blog_card": "BlogCard-1",
            "footer_component": "FooterVar1",
            "footer_menu": [
                {
                    "isDefault": false,
                    "sub_menu": [
                        {
                            "link": "/buying-homes-in-lekki",
                            "title": "Buying Homes"
                        },
                        {
                            "link": "/selling-homes-in-lekki",
                            "title": "Selling Homes"
                        }
                    ],
                    "title": "Discover Services"
                },
                {
                    "isDefault": true,
                    "sub_menu": [
                        {
                            "link": "/buying-homes-in-lekki",
                            "title": "Buying Homes"
                        },
                        {
                            "link": "/selling-homes-in-lekki",
                            "title": "Selling Homes"
                        }
                    ],
                    "title": "Popular Links"
                },
                {
                    "isDefault": false,
                    "sub_menu": [
                        {
                            "link": "/aja-properties",
                            "title": "Aja"
                        },
                        {
                            "link": "/lekki-properties",
                            "title": "Lekki"
                        }
                    ],
                    "title": "Popular Areas In Lagos"
                }
            ],
            "header_component": "Header-1",
            "is_default": "No",
            "name": "theme name here",
            "nav_component": "NavVar1",
            "pages": [],
            "primary_color": "green-600",
            "primary_font": "Poppins",
            "property_card": "PropertyCard-1",
            "secondary_color": "gray-900",
            "secondary_font": "Jost",
            "service_card": "ServiceCard-1",
            "solid_primary_color": "sky-600",
            "solid_secondary_color": "blue-500",
            "solid_sencondary_color": "gray-800",
            "solid_tetiary_color": "amber-600",
            "tetiary_color": "fuchsia-500",
            "theme_prefix": "",
            "top_menu": [
                {
                    "isDefault": true,
                    "link": "/",
                    "title": "Home"
                },
                {
                    "isDefault": true,
                    "sub_menu": [
                        {
                            "link": "/buying-homes-in-lekki",
                            "title": "Buying Homes"
                        },
                        {
                            "link": "/selling-homes-in-lekki",
                            "title": "Selling Home"
                        },
                        {
                            "link": "/property-mortgage",
                            "title": "Mortgage"
                        }
                    ],
                    "title": "Our Services"
                },
                {
                    "sub_menu": [
                        {
                            "link": "/more-menu-1",
                            "title": "More Menu 1"
                        },
                        {
                            "link": "/more-menu-2",
                            "title": "More Menu 2"
                        }
                    ],
                    "title": "New Menu"
                },
                {
                    "isDefault": false,
                    "link": "/contact-us",
                    "title": "Contact Us"
                }
            ],
            "version": "1.0.1"
        },
        "title": "Initial Theme Test",
        "user_id": 1,
        "website": "https://themetest.com"
    };
		const pageData = {
        "isHome": true,
        "metaDescription": "Discover premium homes, luxury apartments, and land for sale in Lagos Nigeria. Buy, rent, or sell properties fast with Nigeria's trusted real estate agency. Expert agents, verified listings in Lekki, Ikoyi, Victoria Island \u0026 more.",
        "nav_bg": "transparent",
        "sections": [
            {
                "props": {},
                "type": "HeaderVar1"
            },
            {
                "props": {
                    "category": "featured_listings",
                    "component": "FeaturedListsingsVar1",
                    "fields": "*",
                    "header": "Featured Listsings",
                    "name": "Featured Listsings",
                    "property_type": "Residential",
                    "sales_type": "For Sale",
                    "size": "8",
                    "status": "Active",
                    "sub_header": "Here are some of our handpicked properties for you.",
                    "type": "section"
                },
                "type": "FeaturedListsingsVar1"
            },
            {
                "props": {
                    "category": "our_services",
                    "component": "OurServicesVar1",
                    "header": "What We Do At Lagos Realty",
                    "name": "Our Services",
                    "show_more": "Yes",
                    "show_more_text": "Show More Services Now",
                    "size": "6",
                    "sub_header": "Our services at Lagos Realty Inc.",
                    "type": "section"
                },
                "type": "OurServicesVar1"
            },
            {
                "props": {
                    "category": "featured_neighborhoods",
                    "component": "NeighborhoodsVar1",
                    "header": "Featured Neighborhoods",
                    "name": "Featured Neighborhoods",
                    "show_more": "Yes",
                    "show_more_text": "Show More Neighborhoods",
                    "size": "6",
                    "sub_header": "Explore our handpicked neighborhoods that define the best of city living.",
                    "type": "section"
                },
                "type": "NeighborhoodsVar1"
            },
            {
                "props": {
                    "category": "blog_posts",
                    "component": "BlogsVar1",
                    "header": "Latest Real Estate News",
                    "name": "Blogs",
                    "show_more": "Yes",
                    "show_more_text": "Read All Posts",
                    "size": "4",
                    "sub_header": "Get Latest Real Estate News Here.",
                    "type": "section"
                },
                "type": "BlogsVar1"
            }
        ],
        "slug": "/home",
        "title": "Lagos Realty: Home Page",
        "uid": "home-page-001"
    };

		return <ClientPage themeData={themeData} pageData={pageData} />;
	}